// These are items that violate one of the common naming conventions and need to
//  be uniquely permitted.
export const PREAPPROVED_ITEMS = [
  'bone pirates necklace',
  'senche-lion tooth tail loop',
  'style page witchmothers servants epaulets',
  'spotless goods signet stamp',
  'prophets axe',
  'wrathsun guards',
  'wrought-iron claw file',
  'stirk fellowship guardian shield',
  'storm shield',
  'ritual daedra skull',
  'telvanni enforcer shield',
  'metal band',
  'oyster shell goblet',
  'recipe psijic ambrosia fragment i',
  'pillagers ring',
  'prophets maul',
  'wamasu hide frilly parasol',
  'the reach treasure map',
  'senche tigerskin bedroll',
  'wolf head wall mount',
  'argonian scale beetle cheese plate',
  'tide-born dagger',
  'wolf head lounge pillow',
  'praxis alinor bookcase wall timeworn',
  'oakfathers retribution shield',
  'stirk fellowship plated boots',
  'monster chokethorn',
  'scrap metal',
  'necklace of torugs pact',
  'mudcrab chitin',
  'senche tiger fang',
  'spirit wardens gloves',
  'the thief gods treasures',
  'scamp head',
  'necklace of the green pact',
  'gnarled bear claw',
  'prophets greatsword',
  'scaly durzog hide',
  'soulcleaver dagger',
  'stuffed scamp head',
  'gold leaf bandages',
  'shrunken werewolf head',
  'style page pirate skeleton shoulder',
  'monolith of storms guards',
  'ravaging ring',
  'magnus lightning staff',
  'seventh legion girdle',
  'seventh legion sash',
  'mushrooms netch hide shade',
  'werewolf hide ring',
  '"barbas" dog collar',
  'moon sugar cane',
  'magnus epaulets',
  'magnus bow',
  'yokudan style flatware',
  'magnus robe',
  'micro etched theories of seht',
  'magnus pauldron',
  'seventh legion gauntlets',
  'soulcleaver sabatons',
  'nix hound food bowl',
  'decorative moody mer false face',
  'guild memo on soul trapping',
  'tide-born helmet',
  'cyrodilic cornbread',
  'grimoire banner bearer',
  'lost amulet',
  'festive fingerbone mouth harp',
  'wrathsun battle axe',
  'wrathsun breeches',
  'wrathsun jerkin',
  'horker ivory handled razor',
  'horker skin drum',
  'gold leaf cabbage bowl',
  'horned owl feathers',
  'finger bone charm',
  'five claws cards',
  'frozen watchers necklace',
  'gee-los claw polish',
  'gold leaf stationery',
  'giant wasp head',
  'cyrodiilic corn bread',
  'bottle of red claw polish',
  'glenmoril wyrd leg cologne',
  'etched troll tooth',
  'domihaus pauldron',
  'dominions ring',
  'dragon scale mushrooms',
  'nobility in decay inferno staff',
  'cast iron toothed spoon',
  'ceremonial shawm for royal feast days',
  'chitinous collapsible razor',
  'chub loon downfeather puff',
  'claw necklace',
  'cold cyrodilic corn bread',
  'color changing ink',
  'telvanni enforcer dagger',
  'soulcleaver gloves',
  'soulcleaver jerkin',
  'gold coast gauntlets',
  'bonemold training sword',
  'cast iron skillet',
  'crosswych knotted rope',
  'affix script off balance',
  'frostbite staff',
  'bonemold stein',
  'zens necklace',
  'alinor bookcase wall timeworn',
  'alinor bookshelf grand full',
  'all flags navy campaign ribbon',
  'apple-bobbing cold iron cauldron',
  'ascendant helm',
  'unopened treasure map',
  'werewolf hide wolfs-head ring',
  'baan dars blessing amulet',
  'blueprint alinor bookshelf polished',
  'blueprint elsweyr bookshelf wooden',
  'oakfathers retribution hat',
  'oakfathers retribution ring',
  'gardener of seasons gauntlets',
  'magnus guards',
  'twisted nose ring',
  'magnus dagger',
]

// These are style names that belong to monster styles and can cause overlap
//  with the bound monster set items.
export const MONSTER_STYLE_NAMES = [
  'shadowrends',
  'mighty chudans',
  'prior thierric',
  'slimecraws',
  'troll kings',
  'nerieneths',
  'lord wardens',
  'swarm mothers',
  'symphony of blades',
  'swarm mothers',
  'the blind',
  'mighty chudan',
  'earthgore',
  'anthelmirs construct',
  'euphotic gatekeeper',
  'bloodspawns',
  'grothdarr',
  'grothdarrs',
  'iceheart',
  'icehearts',
  'ilambris',
  'infernal guardian',
  'domihaus',
  'kjalnars nightmare',
  'balorgh',
  'grundwulf',
  'valkyn skorias',
  'magma incarnate',
  'reawakened hierophant',
  'lord warden',
  'velidreth',
  'vykosa',
  'nerieneth',
  'sentinel of rkugamz',
  'selene',
  'maw of the infernal',
  'roksa the warped',
  'pirate skeletons',
  'spawn of mephala',
  'stormfist',
  'slimecraw',
  'sellistrix',
  'shadowrend',
  'baron zaudrus',
  'molag kenas',
  'velidreths',
  'bar-sakka',
]

// These are style sets which use naming convention `/Style Page: .*/`
export const STYLE_NAMES = [
  'covenant banner-bearer',
  'witchmothers servants',
  'tavas goshawk',
  'the maelstroms',
  'opal ilambris',
  'tree-sap legion',
  'pact banner-bearer',
  ' chitinous',
  'abnur tharns',
  'apocrypha expedition',
  'archdruid devyric',
  'arkay unending cycle',
  'ashen militia',
  'ayleid lich',
  'balorgh',
  'barsakka',
  'basaltblood warrior',
  'basalt-blood warrior',
  'black drake clanwrap',
  'black gem monstrosity',
  'bloodspawn',
  'bonemold',
  'bristleback hunter',
  'cadwells',
  'chitinous',
  'chokethorn',
  'clawdance acolyte',
  'claw-dance acolyte',
  'covenant banner bearer',
  'crowborne hunter',
  'dapper daredevil',
  'doctrine ordinator',
  'dominion banner bearer',
  'dovahs duul',
  'earthbone ayleid',
  'ebonsteel knight',
  'eldertide',
  'eltheric revenant',
  'encratiss behemoth',
  'engine guardian',
  'euphotic gatekeeper',
  'evergloam champion',
  'evergreen',
  'fanged worm',
  'fish boon pioneer',
  'frandars tribute',
  // 'gardener of seasons',
  'glenmoril wyrd',
  'gloamsedge',
  'gold road dragoon',
  'gold road dragoon jack',
  'grave dancer',
  'grothdarr',
  'grundwulf',
  'hearts day duelist',
  'high rock spellsword',
  'horned dragon',
  'house dufort banneret',
  'imperial champion',
  'gardener of seasons',
  'jazennji siir',
  'jephrine paladin',
  'jesters aldmeri mimicry',
  'jesters covenant mimicry',
  'jesters pact mimicry',
  'jesters seeker suit',
  'kargaeda',
  'kjalnars nightmare',
  'knight of the circle',
  'knights of the scythe',
  'kragh',
  'kwama miners kit',
  'lady thorn',
  'legacy of the draoife',
  'legion zero',
  'legion zero vigiles',
  'light of knowledge',
  'lion guard captain',
  'lyris titanborns',
  'maarselok',
  'magma incarnate',
  'maw of the infernal',
  'mighty chudan',
  'monolith of storms',
  'morningstar frostwear',
  'mother ciannait',
  'nazaray',
  'nibenese court wizard',
  'nightflame',
  'nightflames',
  'nord carved',
  'oaken order',
  'old orsinium',
  'one bad knight',
  'opal bloodspawn',
  'opal chokethorn',
  'opal domihaus',
  'opal earthgore',
  'opal engine guardian',
  'opal iceheart',
  'opal ilambris',
  'opal lord warden',
  'opal lord wardens',
  'opal nightflame',
  'opal rkugamz sentinel',
  'opal scourge harvester',
  'opal swarm mother',
  'opal troll king',
  'opal troll kings',
  'opal velidreth',
  'orpheon the tactician',
  'ozezan the inferno',
  'pact banner bearer',
  'pelins paragon',
  'pirate skeleton',
  'pirate skeletons',
  'nobility in decay',
  'prior thierric',
  'prophets',
  'psijic psion',
  'yffres fallen-wood',
  // 'reawakened hierophant',
  'regal regalia',
  'rkindaleft dwarven',
  'roksa the warped',
  'saarthal scholar',
  'saberkeel',
  'sai sahans',
  'sancre tor sentry',
  'scourge harvester',
  'second legion',
  'second seed',

  'skaal explorer',
  'snowhawk mage',
  'soulcleaver',
  'sovngarde stalwart',
  'spawn of mephala',
  'squall of retribution',
  'stonekeeper',
  'stormfist',
  'swarm mother',
  'swarm mothers',
  'symphony of blades',
  'tavas goshawk',
  'thane of falkreath',
  'the blind',
  'thurvokun',
  'tools of domination',
  'treesap legion',
  'tremorscale',
  'troll king',
  'truth in wisdom',
  'wickerchain soul',
  'witchmothers servants',
  'valkyn skorias',
  'worm cult hunter',
  'wormwrithe',
  'wrathsun',
  'yffres fallenwood',
  'zaan',
  'zenithar battlesmith',
  'dominion banner-bearer',
].concat(MONSTER_STYLE_NAMES)

export const STYLE_BOOKS: [string, number][] = [
  ['high elf', 1],
  ['dark elf', 2],
  ['wood elf', 3],
  ['nord', 4],
  ['breton', 5],
  ['redguard', 6],
  ['khajiit', 7],
  ['orc', 8],
  ['argonian', 9],
  ['imperial', 10],
]

export const CRAFTING_MOTIFS: [string, number][] = STYLE_BOOKS.concat([
  // High specificity motif names.
  ['ancestral akaviri', 92],
  ['arkthzand armory', 96],

  // base game & early
  ['ancient elf', 11],
  ['barbaric', 12],
  ['primal', 13],
  ['dwemer', 15],
  ['glass', 16],
  ['xivkyn', 17],
  ['akaviri', 18],
  ['mercenary', 19],
  ['yokudan', 20],
  ['ancient orc', 21],
  ['trinimac', 22],
  ['malacath', 23],
  ['outlaw', 24],
  ['aldmeri dominion', 25],
  ['daggerfall covenant', 26],
  ['ebonheart pact', 27],
  ['ra gada', 28],
  ['soul shriven', 29],
  ['morag tong', 30],
  ['skinchanger', 31],
  ['abahs watch', 32],
  ['thieves guild', 33],
  ['assassins league', 34],
  ['dro mathra', 35],
  ['dro-mathra', 35],
  ['dark brotherhood', 36],
  ['ebony', 37],
  ['draugr', 38],
  ['minotaur', 39],
  ['order of the hour', 40],
  ['order hour', 40],
  ['celestial', 41],

  // Morrowind + after
  ['buoyant armiger', 47],
  ['ashlander', 48],
  ['telvanni', 50],
  ['hlaalu', 51],
  ['redoran', 52],
  ['bloodforge', 54],
  ['dreadhorn', 55],
  ['apostle', 56],
  ['ebonshadow', 57],
  ['fang lair', 58],
  ['scalecaller', 59],
  ['psijic', 61],
  ['sapiarch', 62],
  ['pyandonean', 64],
  ['huntsman', 65],
  ['silver dawn', 66],
  ['welkynar', 67],
  ['honor guard', 68],
  ['dead water', 69],
  ['dead-water', 69],
  ['elder argonian', 70],
  ['coldsnap', 71],
  ['meridian', 72],
  ['anequina', 73],
  ['pellitine', 74],
  ['sunspire', 75],
  ['dragonguard', 76],
  ['stags of zen', 77],
  ['refabricated', 79],
  ['shield of senchal', 80],
  ['new moon priest', 81],
  ['icereach coven', 82],
  ['blackreach vanguard', 84],
  ['greymoor', 85],
  ['sea giant', 86],
  ['ancestral nord', 87],
  ['ancestral orc', 88],
  ['ancestral high elf', 89],

  ['hazardous alchemy', 91],

  // Blackreach → Deadlands → Ascending Tide
  ['arkthzand armory', 96],
  ['wayward guardian', 97],
  ['house hexos', 98],
  ['waking flame', 99],
  ['true sworn', 100],
  ['true-sworn', 100],
  ['ivory brigade', 101],
  ['sul xan', 102],
  ['sul-xan', 102],
  ['black fin legion', 103],
  ['ancient daedric', 104],
  ['crimson oath', 105],
  ['silver rose', 106],
  ['annihilarchs chosen', 107],
  ['dreadsails', 110],
  ['ascendant order', 111],

  ['drowned mariner', 116],
  ['firesong', 117],

  // High Isle → Necrom → Scions → Fallen Banners
  ['house mornard', 118],
  ['clan dreamcarver', 121],
  ['dead keeper', 122],
  ['kindreds concord', 123],
  ['the recollection', 124],
  ['blind path cultist', 125],
  ['exiles revenge', 130],
  ['militant monk', 131],
  ['stirk fellowship', 132],
  ['coldharbour dominator', 133],

  ['tide born', 134],
  ['tide-born', 134],
  ['black soul gem', 135],
  ['voskrona guardian', 136],

  // Moved to end for filtering.

  // add these
  ['hollowjack', 42],
  ['grim harlequin', 43],
  ['silken ring', 44],
  ['mazzatun', 45],
  ['frostcaster', 46],
  ['militant ordinator', 49],
  ['tsaesci', 53],
  ['worm cult', 60],
  ['dremora', 63],
  ['moongrave fane', 78],
  ['pyre watch', 83],
  ['thorn legion', 90],
  ['ancestral akaviri', 92],
  ['ancestral breton', 93],
  ['ancestral reach', 94],
  ['nighthollow', 95],
  ['fargrave guardian', 108],
  ['syrabanic marine', 112],
  ['steadfast society', 113],
  ['systres guardian', 114],
  ['yffres will', 115],
  ['blessed inheritor', 119],
  ['scribes of mora', 120],
  ['dead keeper', 122],
  ['kindreds concord', 123],
  ['shardborn', 126],
  ['west weald legion', 127],
  ['lucent sentinel', 128],
  ['hircine bloodhunter', 129],
])

export const SETS_TO_ADD_THE = [
  '6th house',
  'abecean',
  'advancing yokeda',
  'air',
  'akaviri war',
  'alchemist',
  'ancestor moth',
  'anchorite',
  'ancient mariner',
  'ancient one',
  'ancients',
  'arch-mage',
  'arch mage',
  'arch silver',
  'archers mind',
  'arena heavy armor',
  'arena jewelry',
  'arena light armor',
  'arena medium armor',
  'arena weapons',
  'arena',
  'armor master',
  'ascendant magus',
  'ascendant',
  'ashabah',
  'askelde men',
  'automaton',
  'ayleid king',
  'ayleids',
  'bad man',
  'bad performance',
  'banished',
  'baron',
  'bay',
  'beast prince',
  'beekeeper',
  'betrayer',
  'black death',
  'black drake',
  'black maw',
  'black rose',
  'black sands',
  'black worm',
  'blind',
  'bloody tusk',
  'bonnie spriggan',
  'breaker',
  'brief queen',
  'broken soul',
  'brute',
  'chieftain',
  'chronicle',
  'circle bow',
  'circle cuirass',
  'circle gauntlets',
  'circle greaves',
  'circle helm',
  'circle maul',
  'circle pauldrons',
  'circle sabatons',
  'circle shield',
  'circle staff',
  'circle sword',
  'citadel',
  'claw',
  'code',
  'combat physician',
  'conspirators',
  'construct',
  'courier',
  'court of contempt',
  'coven',
  'crazed',
  'crescent moon',
  'crimson oath',
  'crocmother',
  'crossing',
  'crucible',
  'crusader',
  'crystal tower',
  'cunning',
  'cured',
  'cygnus irregulars',
  'daedra',
  'daedroth',
  'daggerfall covenant',
  'dagon breaker',
  'darkest seducer',
  'dawn',
  'day rack',
  'deadlands',
  'defender',
  'defiler',
  'depths',
  'desert faded',
  'desert flame faded',
  'desert rose',
  'devourer',
  'divine poster',
  'divines',
  'doomcrag',
  'dragon',
  'dreugh king slayer',
  'duchess',
  'dunmeri great houses',
  'dwemer i a',
  'dwemer i b',
  'dwemer ii',
  'dwemer iii',
  'dwemer iv',
  'dwemer v',
  'dwemer vi',
  'dwemer viii',
  'dwemer x',
  'dwemer xi',
  'eight divines',
  'elder scrolls',
  'elder sister',
  'eleventh force',
  'emancipator',
  'empire',
  'endless',
  'essence thief',
  'eternal yokeda',
  'ever-shrouded',
  'ever shrouded',
  'ever shrouded',
  'exarch',
  'eye',
  'eyes of mara',
  'fallen comrade',
  'fallen knight',
  'fallen wastes',
  'falmer',
  'false alkosh',
  'fane',
  'fang',
  'fate eater',
  'fighters guild pt 1',
  'fighters guild pt 2',
  'fire',
  'first altmeri landfall',
  'first mane',
  'first monastic',
  'first titan',
  'five companions',
  'flame tabard',
  'footman',
  'forest protector',
  'forest wraith heavy armor',
  'forest wraith jewelry',
  'forest wraith light armor',
  'forest wraith medium armor',
  'forest wraith weapons',
  'forest wraith',
  'forgotten',
  'four winds',
  'fractured mind',
  'furious one',
  'gears',
  'general',
  'ghost knight',
  'ghost snake',
  'glittering goad',
  'gold coast',
  'golden era',
  'good daedra',
  'gorethief',
  'grasp amulet',
  'grasp axe',
  'grasp battle axe',
  'grasp bow',
  'grasp breeches',
  'grasp dagger',
  'grasp epaulets',
  'grasp gloves',
  'grasp greatsword',
  'grasp hat',
  'grasp ice staff',
  'grasp inferno staff',
  'grasp jerkin',
  'grasp lightning staff',
  'grasp mace',
  'grasp maul',
  'grasp restoration staff',
  'grasp ring',
  'grasp robe',
  'grasp sash',
  'grasp shield',
  'grasp shoes',
  'grasp sword',
  'gray host',
  'great tree',
  'green pact bosmer',
  'green pact',
  'green pact',
  'green sister',
  'grove',
  'gryphon',
  'guardian',
  'hallowed',
  'harbinger item',
  'harbinger',
  'hatchlings shell',
  'hawks eye',
  'healer',
  'heartland',
  'henge',
  'hist axe',
  'hist battle axe',
  'hist bow',
  'hist cuirass',
  'hist dagger',
  'hist gauntlets',
  'hist girdle',
  'hist greatsword',
  'hist greaves',
  'hist helm',
  'hist ice staff',
  'hist inferno staff',
  'hist lightning staff',
  'hist mace',
  'hist maul',
  'hist necklace',
  'hist pauldron',
  'hist restoration staff',
  'hist ring',
  'hist sabatons',
  'hist shield',
  'hist sword',
  'hist',
  'hive lord',
  'holdfast',
  'hollow crown',
  'hollow hunt',
  'hollow moon',
  'houndslayer',
  'houndsworn',
  'hour banner large',
  'hour candlestick',
  'hour prayer candle',
  'hour rug winged',
  'hour',
  'hunt',
  'huntbeast',
  'ideal masters',
  'iliac bay',
  'immortal yokeda',
  'imperium',
  'impostor',
  'indrik',
  'infallible aether',
  'infernal mask',
  'infernal pauldron',
  'infernal shoulder',
  'infernals arm cops',
  'infernals epaulets',
  'infernals guise',
  'infernals hat',
  'infernals helm',
  'infernals helmet',
  'infernals mask',
  'infernals pauldron',
  'infernals shoulder',
  'infernals visage',
  'initiate',
  'insatiable',
  'ivory brigade',
  'jilted',
  'juggernaut',
  'kalmur',
  'keepers',
  'knight',
  'knightmare',
  'kynmarchers cruelty',
  'lamia queen',
  'lamia slayer',
  'last captain',
  'legion',
  'lich',
  'light',
  'lonely traveler',
  'lost fleet',
  'lost legion arm cops',
  'lost legion axe',
  'lost legion battle axe',
  'lost legion belt',
  'lost legion boots',
  'lost legion bow',
  'lost legion bracers',
  'lost legion breeches',
  'lost legion cuirass',
  'lost legion dagger',
  'lost legion epaulets',
  'lost legion gauntlets',
  'lost legion girdle',
  'lost legion gloves',
  'lost legion greatsword',
  'lost legion greaves',
  'lost legion guards',
  'lost legion hat',
  'lost legion heavy armor',
  'lost legion helm',
  'lost legion helmet',
  'lost legion ice staff',
  'lost legion inferno staff',
  'lost legion jack',
  'lost legion jerkin',
  'lost legion jewelry',
  'lost legion light armor',
  'lost legion lightning staff',
  'lost legion mace',
  'lost legion maul',
  'lost legion medium armor',
  'lost legion necklace',
  'lost legion pauldron',
  'lost legion restoration staff',
  'lost legion ring',
  'lost legion robe',
  'lost legion sabatons',
  'lost legion sash',
  'lost legion shield',
  'lost legion shoes',
  'lost legion sword',
  'lost legion weapons',
  'lost legion',
  'lost',
  'lunar bastion',
  'lunar champion deeds',
  'lurcher',
  'lutepicker',
  'mages guild',
  'magicka furnace',
  'man-bull',
  'man bull',
  'man bull',
  'mane',
  'martyr',
  'maw',
  'mirage faded',
  'mock turtle',
  'moons',
  'morag tong',
  'morning',
  'mundus',
  'necromancer',
  'nereids',
  'nest',
  'netchs touch',
  'night hunter',
  'night mother',
  'noble duelist',
  'nobles conquest',
  'nord cultural exchange',
  'north',
  'numidium',
  'oasis faded',
  'obsidian scar',
  'onslaught',
  'order of diagna',
  'orders wrath',
  'palace of ysgramor',
  'pariah',
  'people',
  'pestilent host',
  'phoenix',
  'planes',
  'potentates',
  'powerful assault',
  'primate tapestry',
  'prisoner',
  'prophet',
  'psijic order',
  'queen disguise kit',
  'queen',
  'quick fox',
  'quiet farewell',
  'ra gada',
  'radiant bastion',
  'rahniza',
  'ranger',
  'ratmaster',
  'rawlith khaj',
  'reach a guide',
  'reach emote',
  'reachmage',
  'realmstrider',
  'reclaimed lesson',
  'red asp',
  'red mountain',
  'resilient yokeda',
  'resolute',
  'return volume 27',
  'return volume 49',
  'return volume 5',
  'riekr king chief',
  'rift',
  'risen',
  'rithana direnada',
  'ritualist',
  'ruckus',
  'sapiarchs refined',
  'scathing mage',
  'schemer',
  'scion',
  'scripts',
  'scrivener',
  'scythe cuirass',
  'scythe gauntlets',
  'scythe girdle',
  'scythe greaves',
  'scythe helmet',
  'scythe pauldrons',
  'scythe sabatons',
  'sea vipers',
  'seducer heavy armor',
  'seducer jewelry',
  'seducer light armor',
  'seducer medium armor',
  'seducer weapons',
  'seducer',
  'senche',
  'sentry',
  'sergeant',
  'serpent',
  'seventh legion',
  'shadow dancer',
  'shadow guard',
  'shadow walker',
  'shalk',
  'sheath',
  'shield breaker',
  'sightless pirate',
  'silent root',
  'silver rose',
  'sisters',
  'skirmisher',
  'smuggler',
  'snake charmer',
  'snake',
  'song of lamae',
  'spectres eye',
  'spider slayer',
  'spirit wardens',
  'spirit within',
  'stalker',
  'star',
  'steadfast',
  'steadfasts largesse',
  'steadfasts munificence',
  'stonechewers',
  'storm knight',
  'storm knights plate',
  'storm night',
  'storm',
  'subservient',
  'sun faded summer',
  'sun faded',
  'sun painting metal',
  'sun',
  'sundered triad',
  'sunrise faded',
  'sunset faded',
  'swampstrider',
  'sweetroll',
  'swift',
  'tamed dunes',
  'tentacles',
  'thief',
  'third house of hist sap',
  'thorn',
  'thousand eyes',
  'three sisters',
  'three',
  'titan',
  'titanborn',
  'tormentor',
  'trainee',
  'trapmaster amulet',
  'trapmaster arm cops',
  'trapmaster axe',
  'trapmaster belt',
  'trapmaster boots',
  'trapmaster bracers',
  'trapmaster dagger',
  'trapmaster guards',
  'trapmaster helmet',
  'trapmaster jack',
  'trapmaster maul',
  'trapmaster restoration staff',
  'trapmaster ring',
  'trapmaster shield',
  'tribal bosmer',
  'tribunal',
  'true path',
  'turning tide',
  'twice-born star',
  'twice born star',
  'twin ambitions',
  'twin sisters',
  'two-fanged snake',
  'two fanged snake',
  'ugly mug',
  'unassailable',
  'unbroken accord',
  'undaunted bastion',
  'undaunted infiltrator',
  'undaunted octagram',
  'undaunted rectangular',
  'undaunted unweaver',
  'undertaker',
  'unfortunate wanderer',
  'unknown queen',
  'unrequited',
  'ursauk amulet',
  'ursauk arm cops',
  'ursauk axe',
  'ursauk battle axe',
  'ursauk belt',
  'ursauk boots',
  'ursauk bow',
  'ursauk bracers',
  'ursauk dagger',
  'ursauk greatsword',
  'ursauk guards',
  'ursauk helmet',
  'ursauk ice staff',
  'ursauk inferno staff',
  'ursauk jack',
  'ursauk lightning staff',
  'ursauk mace',
  'ursauk maul',
  'ursauk restoration staff',
  'ursauk ring',
  'ursauk shield',
  'ursauk sword',
  'valenheart',
  'valiant',
  'vampire lord',
  'vampires cloak',
  'veiled heritance',
  'vents',
  'vicious ophidian',
  'viper',
  'voidcaller',
  'voidguide',
  'voracious',
  'wandering hero',
  'war maiden',
  'warlock',
  'warrior-poet',
  'warrior poet',
  'waylaid traveler of salvation',
  'waylaid traveler',
  'weald gear',
  'weald',
  'west',
  'westwind lighthouse',
  'wild hunt',
  'wilder',
  'wilderqueen',
  'willows path',
  'wind',
  'winterbourne',
  'wise',
  'witch hunter',
  'withered hand',
  'wolf-father',
  'wolf father',
  'wooded eye',
  'world',
  'worm cult',
  'worm cult',
  'worm',
  'worms tongue',
  'wyrd tree',
  'yokeda',
  'yokudan war gods',
  'younger sister',
]

// These are sets that take the form `${item} of ${set}` instead of the standard
//  `${set} ${item}`.
export const SETS_TO_FLIP = SETS_TO_ADD_THE.concat([
  'rid-thar-ridatta',
  'zymel hriz',
  'menta na',
  'giant toes',
  'torugs pact',
  'everfrost',
  'aiden direnni',
  'snow elf ears',
  'summersets champion',
  'fulmination',
  'blue ice',
  'sardavar',
  'silver rose',
  'unstable elements',
  'embers',
  'almalexias mercy',
  'critical ripos',
  'critical rip',
  'critical r',
  'three mercies',
  'shadow',
  'shadows',
  'storms',
  'clomping',
  'kynes flight',
  'mazzatun',
  'nikulas',
  'sacrifice',
  'baan dars blessing',
  'transmutation',
  'vicious death',
  'halmer stormhand',
  'mephalas hand',
  'morihaus',
  'affliction',
  'leeching',
  'shabnam',
  'cyrodiils crest',
  'sheer venom',
  'rage',
  'akatoshs blessing',
  'syvarras scales',
  'fingers',
  'adroitness',
  'medusa',
  'scavenging demise',
  'permafrost',
  'salvation',
  'toxic defiance',
  'kynes kiss',
  'duroks bane',
  'doumant belland',
  'oblivion',
  'rime',
  'twilight remedy',
  'prayer',
  'unfathomable darkness',
  'truth',
  'necropotence',
  'house selos',
  'mending',
  'stendarr',
  'stendarrs mercy',
  'sanctuary',
  'glory',
  'vengeance leech',
  'gryphons reprisal',
  'imperial wrath',
  'night terror',
  'rushing agony',
  'alkosh',
  'soulshine',
  'ursus',
  'willpower',
  'tavas favor',
  'martial knowledge',
  'succession',
  'fury',
  'endurance',
  'elf bane',
  'deadfire',
  'aetherial ascension',
  "akatosh's law",
  // "baan dar's blessing",
  "bahsei's mania",
  'bats',
  'bulwark ruination',
  'catalyst',
  'conflagration',
  'critical riposte',
  'dark convergence',
  "diamond's victory",
  "dragon's appetite",
  "drake's rush",
  'eternal vigor',
  'explosive rebuke',
  'frostbite',
  'grave inevitability',
  'high isle',
  'iron flask',
  'kings',
  'kyne',
  "kyne's wind",
  "marauder's haste",
  "nocturnal's ploy",
  // "oakfather's retribution",
  "phylactery's grasp",
  "red eagle's fury",
  "serpent's disdain",
  'shared pain',
  "spriggan's vigor",
  "stone's accord",
  "sul-xan's torment",
  'the alchemist',
  'the depths',
  'the gorethief',
  "the kynmarcher's cruelty",
  "the order's wrath",
  'the pestilent host',
  'the radiant bastion',
  'the ritualist',
  'the silver rose',
  'the turning tide',
  'the voidcaller',
  'the weald',
  'true-sworn fury',
  "winter's respite",
  'wretched vitality',
  "z'en",
  'bahrahas curse',
  // 'baan dars blessing',
  'aetherial ascension',
  'akatoshs law',
  'alessias bulwark',
  'alteration mastery',
  'ambition',
  'ashen grip',
  'beckoning steel',
  'bulwark ruination',
  'clan shatul',
  'clan tumnosh',
  'corrupted springs',
  'corruptions end',
  'critical riposte',
  'cyrodiils crest',
  'cyrodiils light',
  'cyrodiils ward',
  'daedric trickery',
  'deaths wind',
  'destruction mastery',
  'dragons appetite',
  'draugr heritage',
  'elastic girth',
  'evermore',
  'faithfulness',
  'fallen ambition',
  'fasallas guile',
  'firsthold',
  'flanking',
  'forbidden knowledge',
  'frostbite',
  'grounding',
  'hundings rage',
  'hist bark',
  'hist sap',
  'imperial physique',
  'inguya',
  'iron flask',
  'smaller carpentry tools',
  'julianos',
  'kagrenacs hope',
  'khalis strength',
  'mechanical acuity',
  'memory',
  'meritorious service',
  'morkuldin',
  'mothers embrace',
  'natures accord',
  'natures fury',
  'nights silence',
  'notched memories',
  'oblivions foe',
  'orgnums scales',
  'penumbra',
  'red eagles fury',
  'redistribution',
  'remembrance',
  'resonance',
  'riften',
  'sancre tor',
  'secundus',
  'serpents disdain',
  'shalidors curse',
  'sizzling',
  'syrabane',
  'the morag tong',
  'tonal dissonance',
  'torugs pact',
  'trials',
  'mothers sorrow',
  'trinimacs valor',
  'twilights embrace',
  'vampires kiss',
  'varens legacy',
  'withering',
  'wretched vitality',
  // 'baan dars blessing',
  'dark convergence',
  'eternal vigor',
  'kynmarchers cruelty',
  'marauders haste',
  'nocturnals ploy',
  'oakfathers retribution',
  'winters respite',
  'agility',
  'mara',
  'akatoshs law',
  'ancient grace',
]).map((i) => i.replace("'", ''))
