const traitIndex: Record<string, number> = {
  powered: 1,
  charged: 2,
  precise: 3,
  infused: 4,
  defending: 5,
  training: 6,
  sharpened: 7,
  decisive: 8,
  intricate: 9,
  ornate: 10,
  sturdy: 11,
  impenetrable: 12,
  reinforced: 13,
  'well fitted': 14,
  invigorating: 17,
  divines: 18,
  healthy: 21,
  arcane: 22,
  robust: 23,
  nirnhoned: 25,
  swift: 28,
  harmony: 29,
  triune: 30,
  bloodthirsty: 31,
  protective: 32,
  quickened: 34,
  prolific: 35,
  focused: 36,
  shattering: 37,
  aggressive: 38,
  soothing: 39,
  augmented: 40,
  bolstered: 41,
  vigorous: 42,
}

const traitLookup = [
  null,
  'powered', // 1,
  'charged', // 2,
  'precise', // 3,
  'infused', // 4,
  'defending', // 5,
  'training', // 6,
  'sharpened', // 7,
  'decisive', // 8,
  'intricate', // 9,
  'ornate', // 10,
  'sturdy', // 11,
  'impenetrable', // 12,
  'reinforced', // 13,
  'well fitted', // 14,
  'training', // 15,
  'infused', // 16,
  'invigorating', // 17,
  'divines', // 18,
  'ornate', // 19,
  'intricate', // 20,
  'healthy', // 21,
  'arcane', // 22,
  'robust', // 23,
  'ornate', // 24,
  'nirnhoned', // 25,
  'nirnhoned', // 26,
  'intricate', // 27,
  'swift', // 28,
  'harmony', // 29,
  'triune', // 30,
  'bloodthirsty', // 31,
  'protective', // 32,
  'infused', // 33,
  // Companion Weapons
  'quickened', // 34,
  'prolific', // 35,
  'focused', // 36,
  'shattering', // 37,
  'aggressive', // 38,
  'soothing', // 39,
  'augmented', // 40,
  'bolstered', // 41,
  'vigorous', // 42,
  'quickened', // 43,
  'prolific', // 44,
  'focused', // 45,
  'shattering', // 46,
  'aggressive', // 47,
  'soothing', // 48,
  'augmented', // 49,
  'bolstered', // 50,
  'vigorous', // 51,
  'quickened', // 52,
  'prolific', // 53,
  'focused', // 54,
  'shattering', // 55,
  'aggressive', // 56,
  'soothing', // 57,
  'augmented', // 58,
  'bolstered', // 59,
  'vigorous', // 60,
]

export const getTraitIdFromString = (trait: string) => traitIndex[trait]
export const getTraitStringFromId = (id: number) => traitLookup.at(id)
export const sanitizeTraitId = (id: number) =>
  getTraitIdFromString(`${getTraitStringFromId(id)}`)
