export const PATREON_LINK = 'https://discord.gg/ZbRPf4gHYX'
export const REDDIT_LINK = 'https://www.reddit.com/r/ESOMarketTracker/'

export const REPORT_A_BUG_LINK =
  'https://discord.com/channels/1113929923518791781/1113930258572378122'

export const SITE_DESCRIPTION =
  "Fight, loot, and profit with Elder Scrolls Online's only full-featured trading utility app."
export const SITE_TITLE = 'ESO Market Tracker'
export const SITE_TITLE_PREFIXED = `${SITE_TITLE} - `
export const CATEGORY_PATH = '/category'

export const getFullPageTitle = (simpleTitle: string) =>
  `${SITE_TITLE_PREFIXED}${simpleTitle}`

export const CATEGORIES = {
  'Mats (Gold)': [
    'Dreugh Wax',
    'Kuta',
    'Rosin',
    'Tempering Alloy',
    'Aetherial Dust',
    'Diminished Aetherial Dust',
    'Perfect Roe',
  ],
  'Mats (Blacksmithing)': [
    'Calcinium Ingot',
    'Calcinium Ore',
    'Dwarven Ingot',
    'Dwarven Oil',
    'Dwarven Ore',
    'Ebony Ore',
    'Galatite Ingot',
    'Galatite Ore',
    'Grain Solvent',
    'High Iron Ore',
    'Honing Stone',
    'Iron Ingot',
    'Iron Ore',
    'Orichalcum Ingot',
    'Orichalcum Ore',
    'Quicksilver Ingot',
    'Rubedite Ingot',
    'Rubedite Ore',
    'Steel Ingot',
    'Voidstone Ore',
  ],
  'Mats (Clothing)': [
    'Ancestor Silk',
    'Cotton',
    'Ebonthread',
    'Elegant Lining',
    'Embroidery',
    'Fell Hide',
    'Fell Hide Scraps',
    'Flax',
    'Hemming',
    'Hide',
    'Hide Scraps',
    'Iron Hide',
    'Iron Hide Scraps',
    'Ironthread',
    'Jute',
    'Kresh Fiber',
    'Leather',
    'Leather Scraps',
    'Raw Ancestor Silk',
    'Raw Cotton',
  ],
  'Companion Gear': [
    'Companions Arm Cops',
    'Companions Axe',
    'Companions Battle Axe',
    'Companions Belt',
    'Companions Boots',
    'Companions Bow',
    'Companions Bracers',
    'Companions Breeches',
    'Companions Cuirass',
    'Companions Dagger',
    'Companions Epaulets',
    'Companions Gauntlets',
    'Companions Girdle',
    'Companions Gloves',
    'Companions Greatsword',
    'Companions Greaves',
    'Companions Guards',
    'Companions Hat',
    'Companions Helm',
    'Companions Helmet',
    'Companions Ice Staff',
    'Companions Inferno Staff',
    'Companions Jack',
    'Companions Jerkin',
    'Companions Lightning Staff',
    'Companions Ring',
    'Companions Robe',
    'Companions Sabatons',
    'Companions Sash',
    'Companions Shield',
    'Companions Shoes',
    'Companions Sword',
  ],
  'Mats (Furnishing)': [
    'Alchemical Resin',
    'Bast',
    'Clean Pelt',
    'Decorative Wax',
    'Heartwood',
    'Mundane Rune',
    'Ochre',
    'Regulus',
  ],
  'Mats (Jewelry)': [
    'Chromium Grains',
    'Chromium Plating',
    'Copper Dust',
    'Copper Ounce',
    'Electrum Dust',
    'Electrum Ounce',
    'Iridium Grains',
    'Iridium Plating',
    'Pewter Dust',
    'Pewter Ounce',
    'Platinum Dust',
    'Platinum Ounce',
    'Silver Dust',
    'Silver Ounce',
    'Terne Grains',
    'Terne Plating',
    'Zircon Grains',
    'Zircon Plating',
  ],
  'Mats (Woodworking)': [
    'Mastic',
    'Pitch',
    'Rough Ash',
    'Rough Beech',
    'Rough Birch',
    'Rough Hickory',
    'Rough Mahogany',
    'Rough Maple',
    'Rough Nightwood',
    'Rough Oak',
    'Rough Ruby Ash',
    'Rough Yew',
    'Sanded Ash',
    'Sanded Beech',
    'Sanded Birch',
    'Sanded Hickory',
    'Sanded Mahogany',
    'Sanded Maple',
    'Sanded Nightwood',
    'Sanded Oak',
    'Sanded Yew',
    'Turpen',
  ],
}

export const TRAIT_LOOKUP = [
  null,
  'powered', // 1,
  'charged', // 2,
  'precise', // 3,
  'infused', // 4,
  'defending', // 5,
  'training', // 6,
  'sharpened', // 7,
  'decisive', // 8,
  'intricate', // 9,
  'ornate', // 10,
  'sturdy', // 11,
  'impenetrable', // 12,
  'reinforced', // 13,
  'well fitted', // 14,
  'training', // 15,
  'infused', // 16,
  'invigorating', // 17,
  'divines', // 18,
  'ornate', // 19,
  'intricate', // 20,
  'healthy', // 21,
  'arcane', // 22,
  'robust', // 23,
  'ornate', // 24,
  'nirnhoned', // 25,
  'nirnhoned', // 26,
  'intricate', // 27,
  'swift', // 28,
  'harmony', // 29,
  'triune', // 30,
  'bloodthirsty', // 31,
  'protective', // 32,
  'infused', // 33,
  // Companion Weapons
  'quickened', // 34,
  'prolific', // 35,
  'focused', // 36,
  'shattering', // 37,
  'aggressive', // 38,
  'soothing', // 39,
  'augmented', // 40,
  'bolstered', // 41,
  'vigorous', // 42,
  'quickened', // 43,
  'prolific', // 44,
  'focused', // 45,
  'shattering', // 46,
  'aggressive', // 47,
  'soothing', // 48,
  'augmented', // 49,
  'bolstered', // 50,
  'vigorous', // 51,
  'quickened', // 52,
  'prolific', // 53,
  'focused', // 54,
  'shattering', // 55,
  'aggressive', // 56,
  'soothing', // 57,
  'augmented', // 58,
  'bolstered', // 59,
  'vigorous', // 60,
]
