#!/usr/bin/env sh

set -e

echo "Injecting version..."

pnpm run inject-version
git add package.json packages/*/package.json

echo "Running tests..."

echo "Running tests with coverage before push..."
pnpm run coverage