#!/usr/bin/env sh

set -e

pnpm lint
pnpm typecheck

echo "Injecting version..."

pnpm run inject-version
git add package.json packages/*/package.json

echo "Running tests..."

echo "Running tests with coverage before push..."
SKIP_SLOW_TESTS=1 pnpm run coverage
sqlite3 data/artifacts/data.sqlite "VACUUM;"