name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Setup project
        uses: ./.github/actions/setup-dependencies

      - name: Build database
        uses: ./.github/actions/build-sqlite

      - name: Run coverage
        uses: ./.github/actions/run-coverage
        with:
          UESP_COOKIE: ${{ secrets.UESP_COOKIE }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy API
        run: cd apps/deployments/api/src/market-tracker-api && npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Addon
        uses: ./.github/actions/upload-eso-addon
        with:
          bnet_username: ${{ secrets.BNET_USERNAME }}
          bnet_password: ${{ secrets.BNET_PASSWORD }}
          addon_id: ${{ secrets.BNET_ADDON_ID }}
          release_note: "Automated upload from ${{github.sha}}"
          publish: "true"
          concurrency: "1"
          cli_uploader_version: "latest"

      - name: Upload sqlite artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-database
          path: data/artifacts/data.sqlite
          if-no-files-found: error
          retention-days: 7

      - name: Create or update rolling release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="latest"
          TITLE="Latest"
          FILE="data.sqlite"

          gh release view "$TAG" >/dev/null 2>&1 || \
            gh release create "$TAG" \
              --title "$TITLE" \
              --notes "The latest pricing information in SQLite format."

          gh release upload "$TAG" "$FILE" --clobber